# Generated by Django 3.2.6 on 2021-09-06 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleRelatedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('open', 'открыто'), ('closed', 'закрыто')], default='open')),
                ('name', models.CharField(max_length=300)),
                ('related_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.examplerelatedmodel')),
            ],
        ),
    ]
