# Generated by Django 3.2.6 on 2021-09-11 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210911_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='till_data',
            field=models.DurationField(default=datetime.timedelta(seconds=1200)),
        ),
    ]
