# Generated by Django 3.2.6 on 2021-09-11 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_till_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='till_data',
            field=models.DurationField(choices=[(datetime.timedelta(days=10), 'малый срок'), (datetime.timedelta(days=21), 'среднии срок'), (datetime.timedelta(days=31), 'большой срок')]),
        ),
    ]
