# Generated by Django 3.2.6 on 2021-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_till_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='published_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
